name: GSPar Build CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: Fix apt on GitHub Actions
      run: sudo gem install apt-spy2 && sudo apt-spy2 fix --commit --launchpad --country=US
    - name: Update apt
      run: sudo apt-get update
    - name: Install OpenCL
      run: sudo apt-get -o Acquire::Retries=3 install opencl-headers nvidia-opencl-dev #nvidia-libopencl1-384
    - name: Install CUDA
      run: sudo apt-get -o Acquire::Retries=3 install nvidia-cuda-dev
    - name: Build library
      run: make
